"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv/config");
const express_1 = __importDefault(require("express"));
const express_fileupload_1 = __importDefault(require("express-fileupload"));
const cors_1 = __importDefault(require("cors"));
const body_parser_1 = __importDefault(require("body-parser"));
const user_api_1 = __importDefault(require("./api/user.api"));
const coins_api_1 = __importDefault(require("./api/coins.api"));
const admin_api_1 = __importDefault(require("./api/admin.api"));
const app = (0, express_1.default)();
const PORT = process.env.PORT || 3030;
app.use((0, cors_1.default)());
app.use(body_parser_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: true }));
app.use((0, express_fileupload_1.default)());
app.use(`/${process.env.API_SECRET_KEY}/user`, user_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/coins`, coins_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/admin`, admin_api_1.default);
app.listen(PORT, () => console.log(`Starting server at http://localhost:${PORT}`));
