"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv/config");
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const body_parser_1 = __importDefault(require("body-parser"));
const user_api_1 = __importDefault(require("./api/user.api"));
const coins_api_1 = __importDefault(require("./api/coins.api"));
const admin_api_1 = __importDefault(require("./api/admin.api"));
const upload_api_1 = __importDefault(require("./api/upload.api"));
const storage_api_1 = __importDefault(require("./api/storage.api"));
const path_1 = require("path");
const auth_api_1 = __importDefault(require("./api/auth.api"));
const app = (0, express_1.default)();
const PORT = process.env.PORT || 3030;
app.use((0, cors_1.default)());
app.use(body_parser_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: true }));
app.use(`/${process.env.API_SECRET_KEY}/user`, user_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/coins`, coins_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/admin`, admin_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/upload`, upload_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/storage`, storage_api_1.default);
app.use(`/${process.env.API_SECRET_KEY}/auth`, auth_api_1.default);
app.use(express_1.default.static("public"));
app.get("/dashboard", (_, res) => {
    res.sendFile((0, path_1.join)(__dirname, "dashboard/index.html"));
});
app.listen(PORT, () => console.log(`Starting server at http://localhost:${PORT}`));
